### ISSUE TITLE
Alex checks words, not intent.

### ISSUE THREAD

**Issue by Qix-** [get-alex/alex#196] opened 2018-09-26 13:23 UTC
Hear me out. This isn't a troll post (I don't troll Github). See the bottom section for suggestions on how to improve Alex.

Also, apologies to anyone named Janet. I don't know any Janet's so I chose that name.

> You're such a pig, Janet. You literally can't get anything right. I hate how you smell terrible all the time. You're trash at your job and you don't deserve to live, and honestly I wish you would jump off a cliff.

That snippet is 100% okay with Alex - not so much as a warning. I don't think anyone would disagree on it being insensitive or inconsiderate.

Now let's take a look at a feasible (but completely made up) paragraph, admittedly worded specifically to upset Alex.

> Harry let his wand flow in the wind, shooting a stream of black vapor high into the air, which colored the night sky in a display of red and yellow flames. He was the master of the curse, making the dementor his slave.

1 'error', 7 'warnings' (quoted because I don't think those terms translate into prose linting and I'm not sure what else to call them):

```
    1:11-1:14 his may be insensitive, use their, theirs, them instead
    1:38-1:46 Be careful with shooting, it’s profane in some cases
    1:59-1:64 Reconsider using black, it may be profane
    1:96-1:103 Be careful with colored, it’s profane in some cases
    1:157-1:159 He may be insensitive, use They, It instead
    1:168-1:174 master / slave may be insensitive, use primary / replica instead
    1:209-1:212 his may be insensitive, use their, theirs, them instead
    1:213-1:218 Don’t use slave, it’s profane
```

First, a tangent - "red" and "yellow" are derogatorily used to refer to Native Americans/Indians and Asians respectively. They aren't highlighted (only white and black are).

I understand the general response to this sort of critique is "you are smarter than the linter" but there are some fundamental problems here:

- Humans that are speaking ill towards one another are not using a linter/do not care about the linter's output - and I didn't have to try very hard _at all_ to write that first paragraph in a way that generated no warnings.
- Humans that care about other humans and do not wish to upset or hurt them are going to communicate in different tones and fashions that are appropriate for different audiences, and a linter such as Alex isn't going to 'change' anything as they are not operating out of malice in the first place. It boils down to whether or not you are attempting to police _words_, or _ideas_ - the former is what Alex is doing but it seems like the project wants to do the latter. This could be much better documented in the readme.
- Checking specific words without surrounding context, intent or etymology (as others have pointed out) doesn't work, the first example above being a testament to that. Even a crude part of speech analysis would have improved at least _one_ of the errors above (`colored`, which in verb form would never be used to describe people of color and thus never considered insensitive to some).
- Moral or ethical concerns aside, some users are going to use Alex as a way to drive profanity filters (e.g. chat applications looking for a way to censor speech) and be subsequently disappointed when `f𝗎ck hіs bitc𝗁` (copy and paste) gets through unscathed. This has been [documented countless times throughout history](https://blog.codinghorror.com/obscenity-filters-bad-idea-or-incredibly-intercoursing-bad-idea/) as something that just doesn't work (though I understand that's not the flagship use-case of Alex) - and those who wish to bypass filters will find a way. Anecdotally, when Plug.DJ was still around they attempted to filter profanity. A Javascript injection (using ye olde `javascript:void(...)` URL handler) was floating around that monitored the outgoing messages and replaced all of the letters with random unicode lookalikes, rendering the entire filter useless.

---

The above two examples are extreme, I understand. At the very least, this is a call to action to add proper documentation of _intent_ and _supported use cases_ as well as differences to the "profanity filter" problem (where it will be misused or bypassed or otherwise ignored).

I'm not here to argue the efficacy of the project, merely to point out that the readme should probably state what you should expect from the project as it's obviously not a silver bullet.

Further, the question of "who decides what's sensitive" is a completely valid concern and it's a little disappointing to see it shot down so quickly in certain places in the tracker. Perhaps adding a section about this in the readme documenting _some_ of the sources for which terms are (dis)allowed to demonstrate that it's not a single opinionated person behind a keyboard making arbitrary decisions, as admittedly that was my first impression upon landing here :)

Just some thoughts.

**Comment by wooorm** [comment] 2018-09-26 20:48
Hey again Josh. I’m sorry, I’m not going to be able to spend as much time on a response as you did on this write-up. I simply don’t have enough time in my life right now as I used to.

I need alex. I needed alex when I wrote my thesis and created alex. My friends need(ed?) alex as well. That’s why it’s here and why it’s open source.

I think the idea of alex is more useful to a lot of people than the implementation. And as you proved with your examples, it’s never going to be a perfect tool. But it is a tool, and it helps, and yes, humans are smarter than this tool. Beep boop. 🤖

1. For your code examples, feel free to create a PR that implements something like [`retext-sentiment`](https://github.com/retextjs/retext-sentiment). Maybe that helps
2. The goal for alex is to make you, as a human, think. We don‘t care about your use case 1 or 4. But your use case 2 (“Humans that care about other humans”), includes me, and others, that do need a little help. I think one part of that is difference in culture. There’s many things that maybe you, as an American (I believe?) don’t need, but that I, as a non-American, could definitely use a hint for.
  For use case 3, sure. Would be helpful, PRs are open 🤷‍♂️

Look, most of this is about docs. We could use some help. I’m going to try and fix some tomorrow. We’re doing hacktoberfest. Feel free to help out, and maybe there’s a t-shirt and some stickers in it for you! Feel free to help! 🎉

**Comment by Qix-** [comment] 2018-09-27 06:40
Hi @wooorm, very thoughtful response.

I know I write super long posts but I'm attempting to approach this thoughtfully and delicately. The last thing I want is to have this issue be misinterpreted as malicious.

With the current climate of varying opinions on identity politics, a post like mine could be considered either insightful or blasphemous, depending on the person. There's really no way to have any degree of opposing viewpoint without being chastised for it on certain platforms, so I'm hoping that's not the case here on Github.

As a member of the LGBT community (I also feel it's worth mentioning I'm a centrist) I've faced both sides of this coin and wish only to prompt meaningful discussion and development in the spirit of improving Alex.

---

> For your code examples, feel free to create a PR that implements something like `retext-sentiment`. Maybe that helps

Yes, absolutely - that's exactly what I was thinking, too. For the use-case of documentation, even the following is not far-fetched to see in documentation:

```
Please only contribute spaces, as tabs are mindless.
```

Alex = 100% okay. `retext-sentiment` = dark orange (on the [demo page](http://retextjs.github.io/retext-sentiment/)).

However there are some _massive_ gaps in [`afinn-165`](https://github.com/words/afinn-165), such as plurality:`F***ing ni***rs.` with the online demo shows as yellow, which I assume means neutral - whereas the singular form of the second word correctly shows red.

I'm not sure if this is the intended scope of `afinn-165` or if that's something that `retext-sentiment` should handle, but it's definitely not intended functionality.

<sup>Disclaimer: I feel the need to mention I do not use or condone racially derogatory language, and anyone that _does_ should open a book at some point in their lives 🙃</sup>

I'm not sure how `afinn-165` classifies words but it's missing a lot of information (words, specifically) to make it useful for NLP in this way, in my opinion. Is it open for PRs?

Also, `F**k you.` by itself shows as neutral, too. I can't imagine that being correct (deep diving into that particular case, `retext-sentiment` appears to ignore things at the very beginning of a sentence).

Just mentioning it here since you're the maintainer of both of those repos. I can open an issue on the respective repositories if you'd like.

---

> There’s many things that maybe you, as an American (I believe?) don’t need, but that I, as a non-American, could definitely use a hint for.

Yep, I'm American :)

I understand, but I can't stress enough that there will be a continual burden of maintenance stemming from (albeit oftentimes harsh and inconsiderate) feedback due to the perceived language or thought policing. It's obvious to me that isn't the point of Alex (in large part because I'm familiar with who you are a few other maintainers are and that they are good people) - however it's understandable that others will not understand that at first glance of the project's description or examples.

I can see the point in helping those that are not fluent with the culture surrounding the English language - and in my _opinion_ (hopefully nothing I'm saying is being taken as authoritative) that's an incredibly useful and valid use-case for Alex to exist and it does a marvelous job at what it does  - however, suggesting incorrect usages of fundamental components and parts of speech within English when evaluating **general prose** is not considered correct English.

> As an aside: **Boogeyman** (as I mentioned above) is decisively male. It's a [very common entity in horror lore](https://en.wikipedia.org/wiki/Bogeyman). It makes no sense as "boogywoman" unless it's a derivative or parody of the common folklore - the boogeyman is _decisively_ male; "boogey", which generally refers to, uh.. mucus from the nose 🤧; or "bogey", which has something to do with golf scoring (sorry golfers, I'm not well versed with that stuff).

This is critique you're going to receive as maintainers of an English 'scoring' package such as Alex, and without properly disclaiming the goals of the package, that criticism will never end.

---

> Look, most of this is about docs.

I understand that. But all I'm pointing out is that the vast majority of people in America right now consider this topic to be **highly controversial** as many people perceive it to be thought- or language-policing without regards toward _intent_ of the message. This is the reason for the troll posts, the controversy, etc.

Suppression of speech is something Alex is going to be labelled as doing, which is why I'm putting **so much** effort into making sure its documentation or functionality (or both, preferably) reflect the true intent of the project.

If you're worried about mis-pronoun-ing an individual who identifies as a gender not conforming to societal norms, then the error message should reflect that.

> Be careful with "he" or "she", as they can incorrectly refer to an individual of a different gender.

This conveys **intent** and situations where problems may arise. If I wrote Harry Potter, I know Harry Potter is a "he" - it's not insensitive to use it. However, I'm not going to assume that an "Alex" that I have not personally met on the other end of an email message is a male or a female and thus this rule _does_ apply.

The same thing can be applied to race.

> "Black", when referring to an individual or a demographic, is considered profane in certain cases.

This conveys **intent**. If I'm talking about the color black (e.g. _this text is black on white_), in no situation is that going to be insensitive towards a particular race.

These are example of how you could _immediately_ improve error messages, if you're interested in that.

---

Without NLP, the problem of **intent** - the whole point of my posting here - is going to cause friction and remain _academically inaccurate_ until the results are more applicable. _"She is black"_ and _"That UI component is black"_ are not equivalent in terms of insensitivity - this is factually undeniable. 

However, Alex marks both as insensitive - which is concerning since that will only confuse users trying to remain culturally sensitive to English speakers due to not knowing the language as well - something you said yourself was a primary use-case for users.

I strongly feel Alex should move away from individual word evaluation and towards a retext solution if your goal is to curb _truly_ insensitive writing.

Writing something such as...

```
The girl had black hair, black nail polish, and black skin.
```

... and getting back an error such as...

```
1:43 - 1:54 Using "black" to refer to an individual or a skin tone may be considered insensitive
```

... using a data structure similar to...

```json
{
    "profanity": {
        "black": "to refer to an individual or a skin tone"
    }
}
```
```javascript
console.log(`Using "${key}"${profanity[key] ? ' ' + profanity[key] : ''} may be considered profane`);
```

... is going to be much more informative, respectful, sensitive and _accurate_, and more applicable to the English language and culture surrounding it.

However, you're _much_ more well-versed in Retext so it's your call as to whether or not this is something you would want to move toward. This also means a sweeping departure from how Alex works currently, in pursuit of more accurate results.

I'd love to work on this personally as Retext seems fun and it would be a good excuse, and I'm sure there would be interest from others as well.

> Feel free to help! 🎉

Absolutely 🙂

**Comment by wooorm** [comment] 2018-09-27 12:42
Thank again Josh. Let’s split this up though.

1.  Investigate sentiment detection
    * investigate if afinn / retext-sentiment are enough
2.  Suppression of speech
    * Could you look into the readme and the website, and open issues for small problems? I’d like to use those issues for hacktoberfest to get first-timers into open source.
    * Bigger stuff could be PRs!
3.  I like your data-model proposal. Could you create another issue, superseding GH-72, with this suggestion?

> Without NLP, the problem of intent - the whole point of my posting here - is going to cause friction and remain academically inaccurate until the results are more applicable. "She is black" and "That UI component is black" are not equivalent in terms of insensitivity - this is factually undeniable.

I think that NLP, or to be more precise, a machine-learned algorithm, will still be insensitive. There are some cases where algorithms report black as bad, and white as okay, or islam as bad, and christianity as good. That’s unrelated to a more sensitive thing though. I’m all for that.

> if your goal is to curb *truly* insensitive writing.

The goal is to help with *accidental* insensitive writing.

> I'd love to work on this personally as Retext seems fun and it would be a good excuse, and I'm sure there would be interest from others as well.

Awesome!!!

**Comment by SleeplessByte** [comment] 2018-09-28 14:19
Hi there! I don't know if it's appropriate to join this conversation and I really don't want to detract form the points being made; as someone who's on the the spectrum and from a blatantly forward (and usually "rude") culture, I was very intrigued seeing this in my feed. 

That said, I think an additional / complementary issue is with the README and the description, which makes Alex pretend to be a single source of truth when it comes to inconsiderate writing, where in fact, as we can see in the comments above, it's merely aiding people to take note of things that could potentially be perceived differently than was intended. I think this is a great thing, and this tool is good to exist, but I am really conflicted about the way its functionality and usage is described.

As for the workings, I think if https://github.com/get-alex/alex/issues/72 were superseded and implemented, this tool would instantly get so much more value for me, as it would help me understand why something could -- accidentally -- be profane or inconsiderate; and that would help until there is something like NLP to guestimate the intent of the writer and guesstimate how it will be perceived by an arbitrary reader. 

Let's not forget that you can make almost áný word in any language be something profane or inconsiderate.

**Comment by wooorm** [comment] 2018-10-01 20:00
I opened a few new issues to individually work on the things I highlighted above. @Qix-, feel free to work on point 2 of https://github.com/get-alex/alex/issues/196#issuecomment-425076007 if you’re into that.

I’m closing this now, and hope to discuss stuff on the new issues!

**Closed by wooorm** 2018-10-01 20:00 UTC
Labels: question
